name: Test

on:
  push:
    branches: [ '12' ]
  pull_request:
    branches: [ '12' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        ruby: [ jruby, ruby-3.1.6 ]
        neo4j: [ 5.23.0 ]
        active_model: [ 7.0.8, 7.1.4, 7.2.1 ]
        include:
          - ruby: ruby-3.2.5
            neo4j: 5.23.0
            active_model: 7.1.4
          - ruby: ruby-3.3.5
            neo4j: 5.23.0
            active_model: 7.1.4
          - ruby: jruby
            java-version: 17
    env:
      NEO4J_VERSION: ${{ matrix.neo4j }}
      ACTIVE_MODEL_VERSION: ${{ matrix.active_model }}
      JRUBY_OPTS: --debug -J-Xmx1280m -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -Xcompile.mode=OFF
    steps:
      - name: Start neo4j
        run: docker run --name neo4j --env NEO4J_AUTH=neo4j/password --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes --env NEO4J_dbms_directories_import= -p7687:7687 -p7474:7474 -v `pwd`/tmp:/var/lib/neo4j/import --rm neo4j:${{ matrix.neo4j }}-enterprise &

      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Set up Java
        uses: actions/setup-java@v3
        if: matrix.java-version
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Install dependencies
        run: bundle update

      - name: Wait for neo4j
        run: while [ $((curl localhost:7474/ > /dev/null 2>&1); echo $?) -ne 0 ]; do sleep 1; done

      - name: Run tests
        run: bundle exec rspec

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}

#      - name: Run tests
#        run: bundle exec rubocop
